export { default as PageHome } from './home'
export { default as PageAbout } from './about'
export { default as PageError404 } from './error404'
export { default as PageContact } from './contact'
export { default as PageTermsAndConditions } from './terms_and_conditions'
export { default as PagePrivacyPolicy } from './privacyPolicy'
export { default as PagePrivate } from './private'
